Areas/Account/Models/Doctor.cs
using MedBrat.Areas.Appointment.Models;
using System.Text.Json.Serialization;

namespace MedBrat.Areas.Account.Models
{
    public class Doctor : User
    {
        public string? Specialization { get; set; }
        [JsonIgnore]
        public List<Patient> Patients { get; set; } = new();
        [JsonIgnore]
        public List<MedRecord> MedRecords { get; set; } = new();
        [JsonIgnore]
        public List<MedTicket> MedTickets { get; set; } = new();

        public int? ClinicId { get; set; }
        [JsonIgnore]
        public Clinic Clinic { get; set; }

        [JsonIgnore]
        public Schedule? Schedule { get; set; }
    }
}

Areas/Account/Models/Patient.cs
using MedBrat.Areas.Appointment.Models;
using System.Text.Json.Serialization;

namespace MedBrat.Areas.Account.Models
{
    public class Patient : User
    {
        [JsonIgnore]
        public List<Doctor> Doctors { get; set; } = new();
        [JsonIgnore]
        public List<MedRecord> MedRecords { get; set; } = new();
        [JsonIgnore]
        public List<MedTicket> MedTickets { get; set; } = new();
    }
}

Areas/Account/Controllers/RecordController.cs
using MedBrat.Areas.Account.Models;
using MedBrat.Areas.Account.ViewModels;
using MedBrat.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MedBrat.Areas.Account.Controllers
{
    [Authorize]
    public class RecordController : Controller
    {
        ApplicationContext _context;

        public RecordController(ApplicationContext dbcontext)
        {
            _context = dbcontext;
        }

        [Authorize(Roles = "doctor")]
        [HttpGet]
        public IActionResult CreateRecord(string? patientName, string? patientPolis)
        {
            if (patientName != null && patientPolis != null)
                return View(new RecordCreationViewModel() { PatientName = patientName, PatientPolis = patientPolis });
            return View();
        }

        [Authorize(Roles = "doctor")]
        [HttpPost]
        public async Task<IActionResult> CreateRecord(RecordCreationViewModel record)
        {
            var doctor = await _context.Doctors
                .Include(d => d.MedRecords)
                .FirstAsync(d => d.Polis == User.Identity.Name);
            var patient = _context.Patients
                .FirstOrDefault(p => p.Polis == record.PatientPolis);
            if (patient != null)
            {
                if (doctor.MedRecords
                    .Where(r => r.PatientId == patient.Id)
                    .Any())
                {
                    ModelState.AddModelError("", "Журнал с данным пациентом уже существует");
                    return View(record);
                }

                if (ModelState.IsValid)
                {
                    doctor.MedRecords.Add(new MedRecord() { Patient = patient });
                    await _context.SaveChangesAsync();
                }
                else return View(record);
            }
            else
            {
                var newPatient = new Patient() 
                { 
                    Name = record.PatientName, 
                    Polis = record.PatientPolis, 
                    Role = _context.Roles.First(r => r.Name == "patient")
                };
                doctor.MedRecords.Add(new MedRecord() { Patient = newPatient });
                await _context.SaveChangesAsync();
                patient = _context.Patients
                    .FirstOrDefault(p => p.Polis == record.PatientPolis);
            }

            return RedirectToAction("Patient", new { patient.Id });
        }

        [Authorize(Roles = "patient")]
        public IActionResult Doctor(int id)
        {
            var patient = _context.Patients
                .Include(p => p.MedRecords)
                .First(p => p.Polis == User.Identity.Name);
            var doctor = _context.Doctors
                .First(d => d.Id == id);
            var mr = patient.MedRecords
                .FirstOrDefault(r => r.DoctorId == id);

            if (mr != null)
            {
                return View(new VisitsViewModel() 
                { 
                    PatientName = patient.Name, 
                    DoctorName = doctor.Name, 
                    Visits = mr.Visits 
                });
            }

            return RedirectToAction("Doctors", "Proflie");
        }

        [Authorize(Roles = "doctor")]
        public IActionResult Patient(int id)
        {
            var doctor = _context.Doctors
                .Include(d => d.MedRecords)
                .First(d => d.Polis == User.Identity.Name);
            var patient = _context.Patients
                .First(p => p.Id == id);
            var mr = doctor.MedRecords
                .FirstOrDefault(r => r.PatientId == id);

            if (mr != null)
            {
                return View(new VisitsViewModel() 
                { 
                    PatientId = id,
                    PatientName = patient.Name, 
                    DoctorName = doctor.Name, 
                    Visits = mr.Visits 
                });
            }

            return RedirectToAction("MissingRecord", new { id });
        }

        [Authorize(Roles = "doctor")]
        public IActionResult MissingRecord(int id)
        {
            var patient = _context.Patients.First(p => p.Id == id);
            return View(Tuple.Create(patient.Name, patient.Polis));
        }

        [Authorize(Roles = "doctor")]
        [HttpGet]
        public IActionResult CreateVisit(int id)
        {
            var patient = _context.Patients.First(p => p.Id == id);

            return View(new VisitCreationViewModel() { PatientName = patient.Name, PatientPolis = patient.Polis });
        }

        [Authorize(Roles = "doctor")]
        [HttpPost]
        public async Task<IActionResult> CreateVisit(VisitCreationViewModel visit)
        {
            var doctor = _context.Doctors
                .Include(d => d.MedRecords)
                .First(d => d.Polis == User.Identity.Name);
            var patient = _context.Patients
                .First(p => p.Polis == visit.PatientPolis);
            doctor.MedRecords
                .First(r => r.PatientId == patient.Id)
                .Visits
                .Add(new Visit()
                {
                    PatientName = patient.Name,
                    DoctorName = doctor.Name,
                    Date = visit.VisitDate,
                    Status = visit.VisitStatus,
                    Conclusion = visit.VisitConclusion
                });

            _context.Notifications.Add(new Notification()
            {
                UserId = patient.Id,
                Sender = doctor.Name,
                Type = "Уведомление",
                Message = "В журнале добавлена новая запись",
                SendingTime = DateTime.Now
            });
            _context.MedRecords.Update(doctor.MedRecords.First(r => r.PatientId == patient.Id));
            await _context.SaveChangesAsync();

            return RedirectToAction("Patient", new { patient.Id });
        }
    }
}

Areas/Account/Views/Record/CreateRecord.cshtml
@model MedBrat.Areas.Account.ViewModels.RecordCreationViewModel

<style>
.field-validation-error {
    color: #b94a48;
}
  
input.input-validation-error {
    border: 1px solid #b94a48;
}
 
.validation-summary-errors {
    color: #b94a48;
}
</style>
<form method="post" asp-anti-forgery="true">
    <div asp-validation-summary="ModelOnly"></div>
        <p>
            <label asp-for="PatientName"></label><br />
            <input type="text" asp-for="PatientName" placeholder="Иванов Иван Иванович" />
            <span asp-validation-for="PatientName"></span>
        </p>
        <p>
            <label asp-for="PatientPolis"></label><br />
            <input type="text" asp-for="PatientPolis" />
            <span asp-validation-for="PatientPolis"></span>
        </p>
        <p>
            <input type="submit" value="Создать"  />
        </p>
</form>
 
@await Html.PartialAsync("_ValidationScriptsPartial")

Areas/Account/Views/Record/CreateVisit.cshtml
@model MedBrat.Areas.Account.ViewModels.VisitCreationViewModel

<style>
.field-validation-error {
    color: #b94a48;
}
  
input.input-validation-error {
    border: 1px solid #b94a48;
}
 
.validation-summary-errors {
    color: #b94a48;
}
</style>
<form method="post" asp-anti-forgery="true">
    <div asp-validation-summary="ModelOnly"></div>
        <p>
            <label asp-for="PatientName"></label><br />
            <input type="text" asp-for="PatientName" placeholder="Иванов Иван Иванович" />
            <span asp-validation-for="PatientName"></span>
        </p>
        <p>
            <label asp-for="PatientPolis"></label><br />
            <input type="text" asp-for="PatientPolis" />
            <span asp-validation-for="PatientPolis"></span>
        </p>
        <p>
            <label asp-for="VisitDate"></label><br />
            <input type="text" asp-for="VisitDate" />
            <span asp-validation-for="VisitDate"></span>
        </p>
        <p>
            <label asp-for="VisitStatus"></label><br />
            <select asp-for="VisitStatus">
                <option selected value="Первое посещение">Первое посещение</option>
                <option value="Повторное посещение">Повторное посещение</option>
                <option value="На учёте">На учёте</option>
            </select>
            <span asp-validation-for="VisitStatus"></span>
        </p>
        <p>
            <label asp-for="VisitConclusion"></label><br />
            <textarea rows="10" cols="90" asp-for="VisitConclusion" style="resize: none;"></textarea>
            <span asp-validation-for="VisitConclusion"></span>
        </p>
        <p>
            <input type="submit" value="Добавить"  />
        </p>
</form>
 
@await Html.PartialAsync("_ValidationScriptsPartial")

Areas/Account/Views/Record/Doctor.cshtml
@model MedBrat.Areas.Account.ViewModels.VisitsViewModel

<h1>Журнал доктора @Model.DoctorName</h1> 

<style>
    input[type=checkbox] {
        position: absolute;
        top: -9999px;
        left: -9999px;
    }
    label { 
        -webkit-appearance: push-button;
        -moz-appearance: button;
        cursor: pointer;
    }

    /* Default State */
    div.visit {
        display: none;
    }

    /* Toggled State */
    input[type=checkbox]:checked ~ div.visit {
        display: block;
    }
</style>
@foreach(var visit in Model.Visits)
{
    var str = visit.Date.ToString() + visit.Status;
    <div class="p-1 px-2 mb-2" style="border:1px solid black; max-width:100%">
        <div class="d-flex justify-content-between">
            <div class="d-inline-flex flex-row">
                <div class="me-4">@visit.Date.ToString("dd MMMM yyyy")</div>
                <div class="me-4">@visit.Status</div>
            </div>
            <div class="d-inline-flex flex-row-reverse">
                <div>
                    <label for="@str">Подробнее</label>
                </div>
            </div>
            
        </div>
        <input type="checkbox" id="@str">
        <div class="visit">
            <div><b>Имя доктора: </b>@visit.DoctorName</div>
            <div><b>Дата посещения: </b>@visit.Date.ToString("dd MMMM yyyy")</div>
            <div><b>Тип посещения: </b>@visit.Status</div>
            <div><b>Заключение: </b>@visit.Conclusion</div>
        </div>
    </div>
}

Areas/Account/Views/Record/MissingRecord.cshtml
@model Tuple<string, string>

<p>У данного пациента отсутствует журнал</p>
<p>Хотите создать новый журнал?</p>
<a asp-area="Account" asp-controller="Record" asp-action="CreateRecord" 
asp-route-patientName=@Model.Item1 
asp-route-patientPolis=@Model.Item2>
    Создать журнал
</a>

Areas/Account/Views/Record/Patient.cshtml
@model MedBrat.Areas.Account.ViewModels.VisitsViewModel

<h1>Журнал пациента @Model.PatientName</h1> 

<style>
    input[type=checkbox] {
        position: absolute;
        top: -9999px;
        left: -9999px;
    }
    label { 
        -webkit-appearance: push-button;
        -moz-appearance: button;
        cursor: pointer;
    }

    /* Default State */
    div.visit {
        display: none;
    }

    /* Toggled State */
    input[type=checkbox]:checked ~ div.visit {
        display: block;
    }
</style>
@foreach(var visit in Model.Visits)
{
    var str = visit.Date.ToString() + visit.Status;
    <div class="p-1 px-2 mb-2" style="border:1px solid black; max-width:100%">
        <div class="d-flex justify-content-between">
            <div class="d-inline-flex flex-row">
                <div class="me-4">@visit.Date.ToString("dd MMMM yyyy")</div>
                <div class="me-4">@visit.Status</div>
            </div>
            <div class="d-inline-flex flex-row-reverse">
                <div>
                    <label for="@str">Подробнее</label>
                </div>
            </div>
            
        </div>
        <input type="checkbox" id="@str">
        <div class="visit">
            <div><b>Имя пациента: </b>@visit.PatientName</div>
            <div><b>Дата посещения: </b>@visit.Date.ToString("dd MMMM yyyy")</div>
            <div><b>Тип посещения: </b>@visit.Status</div>
            <div><b>Заключение: </b>@visit.Conclusion</div>
        </div>
    </div>
}

<div style = "text-align:center">
    <a class="nav-link m-1" asp-area="Account" asp-controller="Record" asp-action="CreateVisit" asp-route-id=@Model.PatientId>
        + Добавить посещение
    </a>
</div>