Models/NotificationViewComponent.cs
using Microsoft.EntityFrameworkCore;

namespace MedBrat.Models
{
    public class NotificationViewComponent
    {
        ApplicationContext _context;

        public NotificationViewComponent(ApplicationContext context)
        {
            _context = context;
        }
        public async Task<string> InvokeAsync(string polis)
        {
            var user = await _context.Users.FirstAsync(u => u.Polis == polis);

            return _context.Notifications.Where(n => n.UserId == user.Id).ToList().Count.ToString();
        }
    }
}

Areas/Account/Controllers/ClinicController.cs
using AutoMapper;
using MedBrat.Areas.Account.Models;
using MedBrat.Areas.Account.ViewModels;
using MedBrat.Areas.Appointment.Models;
using MedBrat.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MedBrat.Areas.Account.Controllers
{
    [Authorize(Roles = "curator")]
    public class ClinicController : Controller
    {
        private readonly IMapper _mapper;
        ApplicationContext _context;

        public ClinicController(ApplicationContext dbcontext, IMapper mapper)
        {
            _context = dbcontext;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var clinic = GetCurrentClinic();
            var doctors = _context.Doctors
                .Where(d => d.ClinicId == clinic.Id)
                .ToList();

            var clinicVM = _mapper.Map<ClinicViewModel>(clinic);
            foreach(var doc in doctors)
            {
                clinicVM.Doctors.Add(new DoctorsRecordViewModel()
                {
                    DoctorId = doc.Id,
                    Name = doc.Name,
                    Specialization = doc.Specialization
                });
            }

            return View(clinicVM);
        }

        [HttpGet]
        public IActionResult EditClinic()
        {
            var clinic = GetCurrentClinic();
            var cities = _context.Cities.ToList();

            ViewBag.Cities = new SelectList(cities, "Name", "Name", clinic.City);

            return View(new ClinicEditViewModel() { Name = clinic.Name, Address = clinic.Address, City = clinic.City.Name });
        }

        [HttpPost]
        public async Task<IActionResult> EditClinic(ClinicEditViewModel clinicEdit)
        {
            var clinic = GetCurrentClinic();
            var city = _context.Cities
                .First(c => c.Name == clinicEdit.City);

            clinic.Name = clinicEdit.Name;
            clinic.Address = clinicEdit.Address;
            clinic.City = city;

            _context.Clinics.Update(clinic);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public IActionResult Doctor(int id)
        {
            var clinic = GetCurrentClinic();
            var doctor = _context.Doctors
                .Where(d => d.ClinicId == clinic.Id)
                .FirstOrDefault(d => d.Id == id);
            if (doctor == null)
                return NotFound();

            var userProfile = _mapper.Map<UserProfileViewModel>(doctor);

            return View(userProfile);
        }

        [HttpGet]
        public IActionResult AddDoctor()
        {
            return View(new DoctorAddViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> AddDoctor(DoctorAddViewModel newDoctor)
        {
            var clinic = GetCurrentClinic();

            if (_context.Users.FirstOrDefault(u => u.Polis == newDoctor.Polis) == null)
            {
                var doctor = _mapper.Map<Doctor>(newDoctor);
                doctor.Clinic = clinic;
                doctor.Role = _context.Roles.First(r => r.Name == "doctor");
                doctor.Schedule = new Schedule();

                _context.Doctors.Add(doctor);
                await _context.SaveChangesAsync();
            }
            else
            {
                ModelState.AddModelError("", "Данный логин уже используется, введите другой");
                return View(newDoctor);
            }

            return Redirect($"/Appointment/Scheduler/EditSchedule?id={_context.Doctors.First(d => d.Polis == newDoctor.Polis).Id}");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteDoctor(string doctorPolis)
        {
            var clinic = GetCurrentClinic();
            var doctor = _context.Doctors
                .Where(d => d.ClinicId == clinic.Id)
                .FirstOrDefault(d => d.Polis == doctorPolis);
            if (doctor == null)
                return NotFound();

            _context.Doctors.Remove(doctor);
            await _context.SaveChangesAsync();

            return Redirect("Index");
        }

        private Clinic GetCurrentClinic()
        {
            var curator = _context.Curators
                .Include(c => c.Clinic)
                .First(c => c.Polis == User.Identity.Name);
            return _context.Clinics
                .Include(c => c.City)
                .First(c => c.Id == curator.ClinicId);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MedBrat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MedBrat.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MedBrat</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Политика</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">О нас</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Partners">Партнёры</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1 flex-row-reverse">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Account" asp-controller="Profile" asp-action="Index">Личный кабинет</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Appointment" asp-controller="Search" asp-action="Cities">Запись на приём</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MedBrat - <a asp-area="" asp-controller="Home" asp-action="Privacy">Политика</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_ProfileMenuPartial.cshtml
@using System.Security.Claims

<nav class="nav flex-column me-5" style="max-width:200px">
  <a class="nav-link" style="border-bottom: 1px solid black" asp-area="Account" asp-controller="Profile" asp-action="Index">Данные</a>
  @switch (User.FindFirst(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value)
    {
        case "patient":
            <a class="nav-link" style="border-bottom: 1px solid black" asp-area="Account" asp-controller="Profile" asp-action="Doctors">Врачи</a>
            <a class="nav-link" style="border-bottom: 1px solid black" asp-area="Appointment" asp-controller="Ticket" asp-action="TicketsOfPatient">Талоны</a>
            break;
        case "doctor":
            <a class="nav-link" style="border-bottom: 1px solid black" asp-area="Account" asp-controller="Profile" asp-action="Patients">Пациенты</a>
            <a class="nav-link" style="border-bottom: 1px solid black" asp-area="Appointment" asp-controller="Ticket" asp-action="TicketsOfDoctor">Талоны</a>
            break;
        case "curator":
            <a class="nav-link" style="border-bottom: 1px solid black" asp-area="Appointment" asp-controller="Scheduler" asp-action="Index">Управление расписанием</a>
            <a class="nav-link" style="border-bottom: 1px solid black" asp-area="Account" asp-controller="Clinic" asp-action="Index">Клиника</a>
            break;
        case "moderator":
            <a class="nav-link" style="border-bottom: 1px solid black" asp-area="Account" asp-controller="Profile" asp-action="Index">Журнал</a>
            <a class="nav-link" style="border-bottom: 1px solid black" asp-area="Account" asp-controller="Profile" asp-action="Index">Запросы</a>
            <a class="nav-link" style="border-bottom: 1px solid black" asp-area="Account" asp-controller="Profile" asp-action="Index">Управление</a>
            break;
        case "admin":
            <a class="nav-link" style="border-bottom: 1px solid black" asp-area="Account" asp-controller="Profile" asp-action="Index">Журнал</a>
            <a class="nav-link" style="border-bottom: 1px solid black" asp-area="Account" asp-controller="Profile" asp-action="Index">Запросы</a>
            <a class="nav-link" style="border-bottom: 1px solid black" asp-area="Account" asp-controller="Profile" asp-action="adminManagment">Управление</a>
            break;
    }
  <a class="nav-link" asp-area="Account" asp-controller="Profile" asp-action="Notifications">Уведомления ( @await Component.InvokeAsync("Notification", User.Identity.Name) )</a>
</nav>