Areas/Account/Models/Doctor.cs
using MedBrat.Areas.Appointment.Models;
using System.Text.Json.Serialization;

namespace MedBrat.Areas.Account.Models
{
    public class Doctor : User
    {
        public string? Specialization { get; set; }
        [JsonIgnore]
        public List<Patient> Patients { get; set; } = new();
        [JsonIgnore]
        public List<MedRecord> MedRecords { get; set; } = new();
        [JsonIgnore]
        public List<MedTicket> MedTickets { get; set; } = new();

        public int? ClinicId { get; set; }
        [JsonIgnore]
        public Clinic Clinic { get; set; }

        [JsonIgnore]
        public Schedule? Schedule { get; set; }
    }
}

Areas/Appointment/Controllers/SchedulerController.cs
using MedBrat.Areas.Account.ViewModels;
using MedBrat.Areas.Account.Models;
using MedBrat.Areas.Appointment.Models;
using MedBrat.Areas.Appointment.ViewModels;
using MedBrat.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MedBrat.Areas.Appointment.Controllers
{
    [Authorize(Roles = "curator")]
    public class SchedulerController : Controller
    {
        ApplicationContext _context;
        public SchedulerController(ApplicationContext dbcontext)
        {
            _context = dbcontext;
        }

        public IActionResult Index(string name)
        {
            var curator = _context.Curators
                .Include(c => c.Clinic)
                .First(u => u.Polis == User.Identity.Name);

            var doctors = _context.Doctors
                .Include(d => d.Schedule)
                .Where(d => d.ClinicId == curator.ClinicId)
                .ToList();

            var doctorsRec = new List<DoctorsRecordViewModel>();

            if (!string.IsNullOrEmpty(name))
            {
                doctors = doctors
                    .Where(d => d.Name!.Contains(name))
                    .ToList();
            }
            foreach (var doc in doctors)
            {
                doctorsRec.Add(new DoctorsRecordViewModel()
                {
                    DoctorId = doc.Id,
                    Name = doc.Name,
                    Specialization = doc.Specialization
                });
            }

            return View(new DoctorsRecordFilterViewModel(doctorsRec, name, curator.Clinic.Name));
        }

        public IActionResult Doctor(int id)
        {
            var doctor = _context.Doctors
                .Include(d => d.Schedule)
                .First(d => d.Id == id);

            return View(Tuple.Create(doctor.Schedule.WeekSchedule, id));
        }

        [HttpGet]
        public IActionResult EditSchedule(int id)
        {
            var schedule = _context.Doctors
                .Include(d => d.Schedule)
                .First(d => d.Id == id)
                .Schedule;

            var scheduleByDays = new List<ScheduleDayEditViewModel>();

            for(var i = 1; i < 6; i++)
            {
                var scheduleDay = new ScheduleDayEditViewModel();
                scheduleDay.Day = i;
                scheduleDay.WorkingHoursStart = "00:00";
                scheduleDay.WorkingHoursEnd = "00:00";

                scheduleByDays.Add(scheduleDay);
            }

            foreach (var day in schedule.WeekSchedule)
            {
                if (day.Value.Any())
                {
                    var scheduleDay = scheduleByDays.First(s => s.Day == day.Key);
                    scheduleDay.IsWorkingDay = true;
                    scheduleDay.WorkingHoursStart = day.Value.First().ToString();
                    scheduleDay.WorkingHoursEnd = day.Value.Last().ToString();
                    scheduleDay.TicketsNumber = day.Value.Count - 1;

                    scheduleByDays[scheduleByDays.FindIndex(s => s.Day == day.Key)] = scheduleDay;
                }
            }

            return View(new ScheduleEditViewModel() { Id = id, Days = scheduleByDays });
        }

        [HttpPost]
        public async Task<IActionResult> EditSchedule(ScheduleEditViewModel editedSchedule)
        {
            var schedule = _context.Doctors
                .Include(d => d.Schedule)
                .First(d => d.Id == editedSchedule.Id)
                .Schedule;

            var newSchedule = new Dictionary<int, List<TimeSpan>>();

            foreach (var day in editedSchedule.Days)
            {
                var dayTickets = new List<TimeSpan>();
                if (day.IsWorkingDay)
                {
                    var startTime = TimeSpan.Parse(day.WorkingHoursStart);
                    var endTime = TimeSpan.Parse(day.WorkingHoursEnd);
                    var ticketInterval = new TimeSpan();
                    if (day.TicketsNumber != 0 && day.TicketsNumber != null && (day.TicketsInterval == 0 || day.TicketsInterval == null))
                    {
                        ticketInterval = (TimeSpan)((endTime - startTime) / day.TicketsNumber!);
                    }
                    else if (day.TicketsInterval != 0 && day.TicketsInterval != null && (day.TicketsNumber == 0 || day.TicketsNumber == null))
                    {
                        ticketInterval = TimeSpan.FromMinutes((double)(day.TicketsInterval!));
                    }
                    else
                    {
                        ModelState.AddModelError("", "Укажите только одно из значений: количество талонов или интервал между талонами");
                        return View(editedSchedule);
                    }

                    while (endTime - startTime >= TimeSpan.Zero)
                    {
                        dayTickets.Add(startTime);
                        startTime += ticketInterval;
                    }
                }

                newSchedule[day.Day] = dayTickets;
            }

            schedule.WeekSchedule = newSchedule;
            if (_context.Schedules.Contains(schedule))
                _context.Schedules.Update(schedule);
            else
                _context.Schedules.Add(schedule);
            await _context.SaveChangesAsync();

            return RedirectToAction("Doctor", new { editedSchedule.Id });
        }
    }
}

Areas/Appointment/Views/Scheduler/Doctor.cshtml
@model Tuple<Dictionary<int, List<TimeSpan>>, int>

@foreach(var day in Model.Item1)
{
    switch (day.Key)
    {
        case 1:
            <div>Пн:</div>
            break;
        case 2:
            <div>Вт:</div>
            break;
        case 3:
            <div>Ср:</div>
            break;
        case 4:
            <div>Чт:</div>
            break;
        case 5:
            <div>Пт:</div>
            break;
    }
    <div class="d-flex my-1">
        @foreach(var time in day.Value)
        {
            <div class="me-2">@time.ToString(@"hh\:mm")</div>
        }
    </div>
}

<a class="nav-link m-1" asp-area="Appointment" asp-controller="Scheduler" asp-action="EditSchedule" asp-route-id=@Model.Item2>
        + Изменить расписание
</a>

Areas/Appointment/Views/Scheduler/EditSchedule.cshtml
@model MedBrat.Areas.Appointment.ViewModels.ScheduleEditViewModel

<style>
.field-validation-error {
    color: #b94a48;
}
  
input.input-validation-error {
    border: 1px solid #b94a48;
}
 
.validation-summary-errors {
    color: #b94a48;
}

input[type=checkbox] {
        position: absolute;
        top: -9999px;
        left: -9999px;
}

input[type=number] {
    width:50px;
}

label { 
    -webkit-appearance: push-button;
    -moz-appearance: button;
    cursor: pointer;
    border: solid 1px black;
}

/* Default State */
div.schedule {
    visibility: hidden;
}

/* Toggled State */
input[type=checkbox]:checked ~ div.schedule {
    visibility: visible;
}
</style>

<h1 class="mb-3">Выберите рабочие дни:</h1>
<form method="post" asp-anti-forgery="true">
    <div asp-validation-summary="ModelOnly"></div>
    <div style="display:none">
        <input type="number" asp-for="Id" value=@Model.Id>
    </div>
    <div class="d-flex mb-2">
        @{
            int i = 0;
        }
        @foreach(var day in Model.Days)
        {
            <div class="me-2">
                <div style="display:none">
                    <input type="number" asp-for=Days[i].Day value=@day.Day>
                </div>
                @switch (day.Day)
                {
                    case 1:
                        <label class="py-1 px-2" for="@day.Day">Пн</label>
                        break;
                    case 2:
                        <label class="py-1 px-2" for="@day.Day">Вт</label>
                        break;
                    case 3:
                        <label class="py-1 px-2" for="@day.Day">Ср</label>
                        break;
                    case 4:
                        <label class="py-1 px-2" for="@day.Day">Чт</label>
                        break;
                    case 5:
                        <label class="py-1 px-2" for="@day.Day">Пт</label>
                        break;
                }
                <input type="checkbox" asp-for=Days[i].IsWorkingDay id="@day.Day">
                <div class="schedule">
                    <span><b>Часы работы:</b></span>
                    <div>
                        c <input type="time" asp-for=Days[i].WorkingHoursStart value=@day.WorkingHoursStart  />
                        <span asp-validation-for=Days[i].WorkingHoursStart></span>
                        до <input type="time" asp-for=Days[i].WorkingHoursEnd value=@day.WorkingHoursEnd  />
                        <span asp-validation-for=Days[i].WorkingHoursEnd></span>  
                    </div>
                    <span><b>
                        Укажите количество<br />
                        талонов или<br />
                        интервал между<br />
                        талонами в минутах:
                    </b></span>
                    <div>
                        <input type="number" asp-for=Days[i].TicketsNumber value=@day.TicketsNumber  />
                        талонов <br />
                        или <br />
                        <input type="number" asp-for=Days[i].TicketsInterval value=@day.TicketsInterval  />
                        мин.
                    </div>
                </div>
            </div>
            i++;
        }
    </div>
    <p>
        <input type="submit" value="Сохранить"  />
    </p>
</form>
 
@await Html.PartialAsync("_ValidationScriptsPartial")

Areas/Appointment/Views/Scheduler/Index.cshtml
@model MedBrat.Areas.Account.ViewModels.DoctorsRecordFilterViewModel
@{
    ViewData["Title"] = "Расписание";
}

<h1>Расписание клиники: "@Model.ClinicName"</h1>

<form class="m-3" method="get">
    <label>Имя: </label>
    <input type="search" class="me-3" name="name" value="@Model.SelectedName" />
    <input class="me-3" type="submit" value="Найти" />
</form>
@foreach(var docRec in Model.Doctors)
{
    <div class="mb-2" style = "border:1px solid black; max-width: 800px">
        <a class="nav-link m-1" asp-area="Appointment" asp-controller="Scheduler" asp-action="Doctor" asp-route-id=@docRec.DoctorId>
            <div><b>@docRec.Name</b></div>
            <div style = "color:grey">@docRec.Specialization</div>
        </a>
    </div>
}

<div style = "text-align:center">
    <a class="nav-link m-1" asp-area="Appointment" asp-controller="Scheduler" asp-action="AddDoctor">
        + Добавить врача
    </a>
</div>